[package]
name = "httpie"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
clap = { version = "4.5.20", features = ["derive"] }
colored = "2"
jsonxf = "1.0.0"
mime = "0.3"
tokio = { version = "1", features = ["full"] }
reqwest = { version = "0.12.9", features = ["json"] }
