[package]
name = "exercise"
version = "0.1.0"
edition = "2021"
[lib]
path = "src/lib.rs"

[dependencies]
rand = "0.8.5"
num = "0.4.0"
twox-hash = "1.6.3"
num-traits = "0.2.19"
num-derive = "0.4.2"
reqwest = { version = "0.12.9", features = ["blocking"] }
html2md = "0.2"
